// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *Credentials           `protobuf:"bytes,1,opt,name=credentials" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCredentialsRequest) Reset() {
	*x = AddCredentialsRequest{}
	mi := &file_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialsRequest) ProtoMessage() {}

func (x *AddCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialsRequest.ProtoReflect.Descriptor instead.
func (*AddCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *AddCredentialsRequest) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type AddCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCredentialsResponse) Reset() {
	*x = AddCredentialsResponse{}
	mi := &file_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialsResponse) ProtoMessage() {}

func (x *AddCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialsResponse.ProtoReflect.Descriptor instead.
func (*AddCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *AddCredentialsResponse) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

type GetCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialsRequest) Reset() {
	*x = GetCredentialsRequest{}
	mi := &file_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsRequest) ProtoMessage() {}

func (x *GetCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *GetCredentialsRequest) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

type GetCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *Credentials           `protobuf:"bytes,1,opt,name=credentials" json:"credentials,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialsResponse) Reset() {
	*x = GetCredentialsResponse{}
	mi := &file_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsResponse) ProtoMessage() {}

func (x *GetCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *GetCredentialsResponse) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *GetCredentialsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DelCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelCredentialsRequest) Reset() {
	*x = DelCredentialsRequest{}
	mi := &file_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCredentialsRequest) ProtoMessage() {}

func (x *DelCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCredentialsRequest.ProtoReflect.Descriptor instead.
func (*DelCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *DelCredentialsRequest) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

type DelCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelCredentialsResponse) Reset() {
	*x = DelCredentialsResponse{}
	mi := &file_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCredentialsResponse) ProtoMessage() {}

func (x *DelCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCredentialsResponse.ProtoReflect.Descriptor instead.
func (*DelCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *DelCredentialsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type AddPaymentCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *PaymentCard           `protobuf:"bytes,1,opt,name=card" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPaymentCardRequest) Reset() {
	*x = AddPaymentCardRequest{}
	mi := &file_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentCardRequest) ProtoMessage() {}

func (x *AddPaymentCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentCardRequest.ProtoReflect.Descriptor instead.
func (*AddPaymentCardRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *AddPaymentCardRequest) GetCard() *PaymentCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type AddPaymentCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPaymentCardResponse) Reset() {
	*x = AddPaymentCardResponse{}
	mi := &file_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentCardResponse) ProtoMessage() {}

func (x *AddPaymentCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentCardResponse.ProtoReflect.Descriptor instead.
func (*AddPaymentCardResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *AddPaymentCardResponse) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *AddPaymentCardResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetPaymentCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentCardRequest) Reset() {
	*x = GetPaymentCardRequest{}
	mi := &file_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentCardRequest) ProtoMessage() {}

func (x *GetPaymentCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentCardRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentCardRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentCardRequest) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

type GetPaymentCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *PaymentCard           `protobuf:"bytes,1,opt,name=card" json:"card,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentCardResponse) Reset() {
	*x = GetPaymentCardResponse{}
	mi := &file_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentCardResponse) ProtoMessage() {}

func (x *GetPaymentCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentCardResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentCardResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *GetPaymentCardResponse) GetCard() *PaymentCard {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *GetPaymentCardResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DelPaymentCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelPaymentCardRequest) Reset() {
	*x = DelPaymentCardRequest{}
	mi := &file_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelPaymentCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPaymentCardRequest) ProtoMessage() {}

func (x *DelPaymentCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelPaymentCardRequest.ProtoReflect.Descriptor instead.
func (*DelPaymentCardRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *DelPaymentCardRequest) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

type DelPaymentCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelPaymentCardResponse) Reset() {
	*x = DelPaymentCardResponse{}
	mi := &file_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelPaymentCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPaymentCardResponse) ProtoMessage() {}

func (x *DelPaymentCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelPaymentCardResponse.ProtoReflect.Descriptor instead.
func (*DelPaymentCardResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *DelPaymentCardResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type AddBinaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bin           *Binary                `protobuf:"bytes,1,opt,name=bin" json:"bin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBinaryRequest) Reset() {
	*x = AddBinaryRequest{}
	mi := &file_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBinaryRequest) ProtoMessage() {}

func (x *AddBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBinaryRequest.ProtoReflect.Descriptor instead.
func (*AddBinaryRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (x *AddBinaryRequest) GetBin() *Binary {
	if x != nil {
		return x.Bin
	}
	return nil
}

type AddBinaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBinaryResponse) Reset() {
	*x = AddBinaryResponse{}
	mi := &file_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBinaryResponse) ProtoMessage() {}

func (x *AddBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBinaryResponse.ProtoReflect.Descriptor instead.
func (*AddBinaryResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{13}
}

func (x *AddBinaryResponse) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *AddBinaryResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetBinaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBinaryRequest) Reset() {
	*x = GetBinaryRequest{}
	mi := &file_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinaryRequest) ProtoMessage() {}

func (x *GetBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBinaryRequest.ProtoReflect.Descriptor instead.
func (*GetBinaryRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{14}
}

func (x *GetBinaryRequest) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

type GetBinaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bin           *Binary                `protobuf:"bytes,1,opt,name=bin" json:"bin,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBinaryResponse) Reset() {
	*x = GetBinaryResponse{}
	mi := &file_gophkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinaryResponse) ProtoMessage() {}

func (x *GetBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBinaryResponse.ProtoReflect.Descriptor instead.
func (*GetBinaryResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{15}
}

func (x *GetBinaryResponse) GetBin() *Binary {
	if x != nil {
		return x.Bin
	}
	return nil
}

func (x *GetBinaryResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DelBinaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelBinaryRequest) Reset() {
	*x = DelBinaryRequest{}
	mi := &file_gophkeeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelBinaryRequest) ProtoMessage() {}

func (x *DelBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelBinaryRequest.ProtoReflect.Descriptor instead.
func (*DelBinaryRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{16}
}

func (x *DelBinaryRequest) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

type DelBinaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelBinaryResponse) Reset() {
	*x = DelBinaryResponse{}
	mi := &file_gophkeeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelBinaryResponse) ProtoMessage() {}

func (x *DelBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelBinaryResponse.ProtoReflect.Descriptor instead.
func (*DelBinaryResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{17}
}

func (x *DelBinaryResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type AddTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *Text                  `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTextRequest) Reset() {
	*x = AddTextRequest{}
	mi := &file_gophkeeper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTextRequest) ProtoMessage() {}

func (x *AddTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTextRequest.ProtoReflect.Descriptor instead.
func (*AddTextRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{18}
}

func (x *AddTextRequest) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

type AddTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTextResponse) Reset() {
	*x = AddTextResponse{}
	mi := &file_gophkeeper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTextResponse) ProtoMessage() {}

func (x *AddTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTextResponse.ProtoReflect.Descriptor instead.
func (*AddTextResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{19}
}

func (x *AddTextResponse) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *AddTextResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextRequest) Reset() {
	*x = GetTextRequest{}
	mi := &file_gophkeeper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextRequest) ProtoMessage() {}

func (x *GetTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextRequest.ProtoReflect.Descriptor instead.
func (*GetTextRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{20}
}

func (x *GetTextRequest) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

type GetTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *Text                  `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextResponse) Reset() {
	*x = GetTextResponse{}
	mi := &file_gophkeeper_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextResponse) ProtoMessage() {}

func (x *GetTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextResponse.ProtoReflect.Descriptor instead.
func (*GetTextResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{21}
}

func (x *GetTextResponse) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *GetTextResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DelTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *string                `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelTextRequest) Reset() {
	*x = DelTextRequest{}
	mi := &file_gophkeeper_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTextRequest) ProtoMessage() {}

func (x *DelTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTextRequest.ProtoReflect.Descriptor instead.
func (*DelTextRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{22}
}

func (x *DelTextRequest) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

type DelTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelTextResponse) Reset() {
	*x = DelTextResponse{}
	mi := &file_gophkeeper_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTextResponse) ProtoMessage() {}

func (x *DelTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTextResponse.ProtoReflect.Descriptor instead.
func (*DelTextResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{23}
}

func (x *DelTextResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type UserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*Credentials         `protobuf:"bytes,1,rep,name=credentials" json:"credentials,omitempty"`
	PaymentCard   []*PaymentCard         `protobuf:"bytes,2,rep,name=paymentCard" json:"paymentCard,omitempty"`
	Binary        []*Binary              `protobuf:"bytes,3,rep,name=binary" json:"binary,omitempty"`
	Text          []*Text                `protobuf:"bytes,4,rep,name=text" json:"text,omitempty"`
	Error         *string                `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataResponse) Reset() {
	*x = UserDataResponse{}
	mi := &file_gophkeeper_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataResponse) ProtoMessage() {}

func (x *UserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataResponse.ProtoReflect.Descriptor instead.
func (*UserDataResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{24}
}

func (x *UserDataResponse) GetCredentials() []*Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *UserDataResponse) GetPaymentCard() []*PaymentCard {
	if x != nil {
		return x.PaymentCard
	}
	return nil
}

func (x *UserDataResponse) GetBinary() []*Binary {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *UserDataResponse) GetText() []*Text {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *UserDataResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         *string                `protobuf:"bytes,1,opt,name=login" json:"login,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Info          *string                `protobuf:"bytes,3,opt,name=info" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_gophkeeper_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{25}
}

func (x *Credentials) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *Credentials) GetInfo() string {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return ""
}

type PaymentCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        *string                `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	ExpMonth      *string                `protobuf:"bytes,2,opt,name=expMonth" json:"expMonth,omitempty"`
	ExpYear       *string                `protobuf:"bytes,3,opt,name=expYear" json:"expYear,omitempty"`
	Cvv           *string                `protobuf:"bytes,4,opt,name=cvv" json:"cvv,omitempty"`
	Holder        *string                `protobuf:"bytes,5,opt,name=holder" json:"holder,omitempty"`
	Alias         *string                `protobuf:"bytes,6,opt,name=alias" json:"alias,omitempty"`
	Info          *string                `protobuf:"bytes,7,opt,name=info" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCard) Reset() {
	*x = PaymentCard{}
	mi := &file_gophkeeper_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCard) ProtoMessage() {}

func (x *PaymentCard) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCard.ProtoReflect.Descriptor instead.
func (*PaymentCard) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{26}
}

func (x *PaymentCard) GetNumber() string {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return ""
}

func (x *PaymentCard) GetExpMonth() string {
	if x != nil && x.ExpMonth != nil {
		return *x.ExpMonth
	}
	return ""
}

func (x *PaymentCard) GetExpYear() string {
	if x != nil && x.ExpYear != nil {
		return *x.ExpYear
	}
	return ""
}

func (x *PaymentCard) GetCvv() string {
	if x != nil && x.Cvv != nil {
		return *x.Cvv
	}
	return ""
}

func (x *PaymentCard) GetHolder() string {
	if x != nil && x.Holder != nil {
		return *x.Holder
	}
	return ""
}

func (x *PaymentCard) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *PaymentCard) GetInfo() string {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return ""
}

type Binary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *string                `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Alias         *string                `protobuf:"bytes,2,opt,name=alias" json:"alias,omitempty"`
	Info          *string                `protobuf:"bytes,3,opt,name=info" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binary) Reset() {
	*x = Binary{}
	mi := &file_gophkeeper_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binary) ProtoMessage() {}

func (x *Binary) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binary.ProtoReflect.Descriptor instead.
func (*Binary) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{27}
}

func (x *Binary) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

func (x *Binary) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *Binary) GetInfo() string {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return ""
}

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *string                `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Alias         *string                `protobuf:"bytes,2,opt,name=alias" json:"alias,omitempty"`
	Info          *string                `protobuf:"bytes,3,opt,name=info" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_gophkeeper_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{28}
}

func (x *Text) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

func (x *Text) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *Text) GetInfo() string {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return ""
}

var File_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x10gophkeeper.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"M\n" +
	"\x15AddCredentialsRequest\x124\n" +
	"\vcredentials\x18\x01 \x01(\v2\x12.proto.CredentialsR\vcredentials\".\n" +
	"\x16AddCredentialsResponse\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"-\n" +
	"\x15GetCredentialsRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"d\n" +
	"\x16GetCredentialsResponse\x124\n" +
	"\vcredentials\x18\x01 \x01(\v2\x12.proto.CredentialsR\vcredentials\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x15DelCredentialsRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\".\n" +
	"\x16DelCredentialsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"?\n" +
	"\x15AddPaymentCardRequest\x12&\n" +
	"\x04card\x18\x01 \x01(\v2\x12.proto.PaymentCardR\x04card\"D\n" +
	"\x16AddPaymentCardResponse\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x15GetPaymentCardRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"V\n" +
	"\x16GetPaymentCardResponse\x12&\n" +
	"\x04card\x18\x01 \x01(\v2\x12.proto.PaymentCardR\x04card\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x15DelPaymentCardRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\".\n" +
	"\x16DelPaymentCardResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"3\n" +
	"\x10AddBinaryRequest\x12\x1f\n" +
	"\x03bin\x18\x01 \x01(\v2\r.proto.BinaryR\x03bin\"?\n" +
	"\x11AddBinaryResponse\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"(\n" +
	"\x10GetBinaryRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"J\n" +
	"\x11GetBinaryResponse\x12\x1f\n" +
	"\x03bin\x18\x01 \x01(\v2\r.proto.BinaryR\x03bin\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"(\n" +
	"\x10DelBinaryRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\")\n" +
	"\x11DelBinaryResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"1\n" +
	"\x0eAddTextRequest\x12\x1f\n" +
	"\x04text\x18\x01 \x01(\v2\v.proto.TextR\x04text\"=\n" +
	"\x0fAddTextResponse\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x0eGetTextRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"H\n" +
	"\x0fGetTextResponse\x12\x1f\n" +
	"\x04text\x18\x01 \x01(\v2\v.proto.TextR\x04text\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x0eDelTextRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"'\n" +
	"\x0fDelTextResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xdc\x01\n" +
	"\x10UserDataResponse\x124\n" +
	"\vcredentials\x18\x01 \x03(\v2\x12.proto.CredentialsR\vcredentials\x124\n" +
	"\vpaymentCard\x18\x02 \x03(\v2\x12.proto.PaymentCardR\vpaymentCard\x12%\n" +
	"\x06binary\x18\x03 \x03(\v2\r.proto.BinaryR\x06binary\x12\x1f\n" +
	"\x04text\x18\x04 \x03(\v2\v.proto.TextR\x04text\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"S\n" +
	"\vCredentials\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\"\xaf\x01\n" +
	"\vPaymentCard\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x1a\n" +
	"\bexpMonth\x18\x02 \x01(\tR\bexpMonth\x12\x18\n" +
	"\aexpYear\x18\x03 \x01(\tR\aexpYear\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\x12\x16\n" +
	"\x06holder\x18\x05 \x01(\tR\x06holder\x12\x14\n" +
	"\x05alias\x18\x06 \x01(\tR\x05alias\x12\x12\n" +
	"\x04info\x18\a \x01(\tR\x04info\"F\n" +
	"\x06Binary\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\"D\n" +
	"\x04Text\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info2\x9c\a\n" +
	"\x11GophKeeperService\x12M\n" +
	"\x0eAddCredentials\x12\x1c.proto.AddCredentialsRequest\x1a\x1d.proto.AddCredentialsResponse\x12M\n" +
	"\x0eGetCredentials\x12\x1c.proto.GetCredentialsRequest\x1a\x1d.proto.GetCredentialsResponse\x12M\n" +
	"\x0eDelCredentials\x12\x1c.proto.DelCredentialsRequest\x1a\x1d.proto.DelCredentialsResponse\x12M\n" +
	"\x0eAddPaymentCard\x12\x1c.proto.AddPaymentCardRequest\x1a\x1d.proto.AddPaymentCardResponse\x12M\n" +
	"\x0eGetPaymentCard\x12\x1c.proto.GetPaymentCardRequest\x1a\x1d.proto.GetPaymentCardResponse\x12M\n" +
	"\x0eDelPaymentCard\x12\x1c.proto.DelPaymentCardRequest\x1a\x1d.proto.DelPaymentCardResponse\x12>\n" +
	"\tAddBinary\x12\x17.proto.AddBinaryRequest\x1a\x18.proto.AddBinaryResponse\x12>\n" +
	"\tGetBinary\x12\x17.proto.GetBinaryRequest\x1a\x18.proto.GetBinaryResponse\x12>\n" +
	"\tDelBinary\x12\x17.proto.DelBinaryRequest\x1a\x18.proto.DelBinaryResponse\x128\n" +
	"\aAddText\x12\x15.proto.AddTextRequest\x1a\x16.proto.AddTextResponse\x128\n" +
	"\aGetText\x12\x15.proto.GetTextRequest\x1a\x16.proto.GetTextResponse\x128\n" +
	"\aDelText\x12\x15.proto.DelTextRequest\x1a\x16.proto.DelTextResponse\x12?\n" +
	"\fListUserData\x12\x16.google.protobuf.Empty\x1a\x17.proto.UserDataResponseB(Z&github.com/Di-nis/gophKeeper/pkg/protob\beditionsp\xe8\a"

var (
	file_gophkeeper_proto_rawDescOnce sync.Once
	file_gophkeeper_proto_rawDescData []byte
)

func file_gophkeeper_proto_rawDescGZIP() []byte {
	file_gophkeeper_proto_rawDescOnce.Do(func() {
		file_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)))
	})
	return file_gophkeeper_proto_rawDescData
}

var file_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_gophkeeper_proto_goTypes = []any{
	(*AddCredentialsRequest)(nil),  // 0: proto.AddCredentialsRequest
	(*AddCredentialsResponse)(nil), // 1: proto.AddCredentialsResponse
	(*GetCredentialsRequest)(nil),  // 2: proto.GetCredentialsRequest
	(*GetCredentialsResponse)(nil), // 3: proto.GetCredentialsResponse
	(*DelCredentialsRequest)(nil),  // 4: proto.DelCredentialsRequest
	(*DelCredentialsResponse)(nil), // 5: proto.DelCredentialsResponse
	(*AddPaymentCardRequest)(nil),  // 6: proto.AddPaymentCardRequest
	(*AddPaymentCardResponse)(nil), // 7: proto.AddPaymentCardResponse
	(*GetPaymentCardRequest)(nil),  // 8: proto.GetPaymentCardRequest
	(*GetPaymentCardResponse)(nil), // 9: proto.GetPaymentCardResponse
	(*DelPaymentCardRequest)(nil),  // 10: proto.DelPaymentCardRequest
	(*DelPaymentCardResponse)(nil), // 11: proto.DelPaymentCardResponse
	(*AddBinaryRequest)(nil),       // 12: proto.AddBinaryRequest
	(*AddBinaryResponse)(nil),      // 13: proto.AddBinaryResponse
	(*GetBinaryRequest)(nil),       // 14: proto.GetBinaryRequest
	(*GetBinaryResponse)(nil),      // 15: proto.GetBinaryResponse
	(*DelBinaryRequest)(nil),       // 16: proto.DelBinaryRequest
	(*DelBinaryResponse)(nil),      // 17: proto.DelBinaryResponse
	(*AddTextRequest)(nil),         // 18: proto.AddTextRequest
	(*AddTextResponse)(nil),        // 19: proto.AddTextResponse
	(*GetTextRequest)(nil),         // 20: proto.GetTextRequest
	(*GetTextResponse)(nil),        // 21: proto.GetTextResponse
	(*DelTextRequest)(nil),         // 22: proto.DelTextRequest
	(*DelTextResponse)(nil),        // 23: proto.DelTextResponse
	(*UserDataResponse)(nil),       // 24: proto.UserDataResponse
	(*Credentials)(nil),            // 25: proto.Credentials
	(*PaymentCard)(nil),            // 26: proto.PaymentCard
	(*Binary)(nil),                 // 27: proto.Binary
	(*Text)(nil),                   // 28: proto.Text
	(*emptypb.Empty)(nil),          // 29: google.protobuf.Empty
}
var file_gophkeeper_proto_depIdxs = []int32{
	25, // 0: proto.AddCredentialsRequest.credentials:type_name -> proto.Credentials
	25, // 1: proto.GetCredentialsResponse.credentials:type_name -> proto.Credentials
	26, // 2: proto.AddPaymentCardRequest.card:type_name -> proto.PaymentCard
	26, // 3: proto.GetPaymentCardResponse.card:type_name -> proto.PaymentCard
	27, // 4: proto.AddBinaryRequest.bin:type_name -> proto.Binary
	27, // 5: proto.GetBinaryResponse.bin:type_name -> proto.Binary
	28, // 6: proto.AddTextRequest.text:type_name -> proto.Text
	28, // 7: proto.GetTextResponse.text:type_name -> proto.Text
	25, // 8: proto.UserDataResponse.credentials:type_name -> proto.Credentials
	26, // 9: proto.UserDataResponse.paymentCard:type_name -> proto.PaymentCard
	27, // 10: proto.UserDataResponse.binary:type_name -> proto.Binary
	28, // 11: proto.UserDataResponse.text:type_name -> proto.Text
	0,  // 12: proto.GophKeeperService.AddCredentials:input_type -> proto.AddCredentialsRequest
	2,  // 13: proto.GophKeeperService.GetCredentials:input_type -> proto.GetCredentialsRequest
	4,  // 14: proto.GophKeeperService.DelCredentials:input_type -> proto.DelCredentialsRequest
	6,  // 15: proto.GophKeeperService.AddPaymentCard:input_type -> proto.AddPaymentCardRequest
	8,  // 16: proto.GophKeeperService.GetPaymentCard:input_type -> proto.GetPaymentCardRequest
	10, // 17: proto.GophKeeperService.DelPaymentCard:input_type -> proto.DelPaymentCardRequest
	12, // 18: proto.GophKeeperService.AddBinary:input_type -> proto.AddBinaryRequest
	14, // 19: proto.GophKeeperService.GetBinary:input_type -> proto.GetBinaryRequest
	16, // 20: proto.GophKeeperService.DelBinary:input_type -> proto.DelBinaryRequest
	18, // 21: proto.GophKeeperService.AddText:input_type -> proto.AddTextRequest
	20, // 22: proto.GophKeeperService.GetText:input_type -> proto.GetTextRequest
	22, // 23: proto.GophKeeperService.DelText:input_type -> proto.DelTextRequest
	29, // 24: proto.GophKeeperService.ListUserData:input_type -> google.protobuf.Empty
	1,  // 25: proto.GophKeeperService.AddCredentials:output_type -> proto.AddCredentialsResponse
	3,  // 26: proto.GophKeeperService.GetCredentials:output_type -> proto.GetCredentialsResponse
	5,  // 27: proto.GophKeeperService.DelCredentials:output_type -> proto.DelCredentialsResponse
	7,  // 28: proto.GophKeeperService.AddPaymentCard:output_type -> proto.AddPaymentCardResponse
	9,  // 29: proto.GophKeeperService.GetPaymentCard:output_type -> proto.GetPaymentCardResponse
	11, // 30: proto.GophKeeperService.DelPaymentCard:output_type -> proto.DelPaymentCardResponse
	13, // 31: proto.GophKeeperService.AddBinary:output_type -> proto.AddBinaryResponse
	15, // 32: proto.GophKeeperService.GetBinary:output_type -> proto.GetBinaryResponse
	17, // 33: proto.GophKeeperService.DelBinary:output_type -> proto.DelBinaryResponse
	19, // 34: proto.GophKeeperService.AddText:output_type -> proto.AddTextResponse
	21, // 35: proto.GophKeeperService.GetText:output_type -> proto.GetTextResponse
	23, // 36: proto.GophKeeperService.DelText:output_type -> proto.DelTextResponse
	24, // 37: proto.GophKeeperService.ListUserData:output_type -> proto.UserDataResponse
	25, // [25:38] is the sub-list for method output_type
	12, // [12:25] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_gophkeeper_proto_init() }
func file_gophkeeper_proto_init() {
	if File_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_proto_rawDesc), len(file_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_proto_depIdxs,
		MessageInfos:      file_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_proto = out.File
	file_gophkeeper_proto_goTypes = nil
	file_gophkeeper_proto_depIdxs = nil
}
