CREATE TABLE IF NOT EXISTS auth (
    id UUID PRIMARY KEY,
    login VARCHAR(255) NOT NULL,
    password_hash BYTEA NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_login ON auth (login);