// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pkg/proto/gophkeeper.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GophKeeperService_AddCredentials_FullMethodName = "/proto.GophKeeperService/AddCredentials"
	GophKeeperService_GetCredentials_FullMethodName = "/proto.GophKeeperService/GetCredentials"
	GophKeeperService_DelCredentials_FullMethodName = "/proto.GophKeeperService/DelCredentials"
	GophKeeperService_AddPaymentCard_FullMethodName = "/proto.GophKeeperService/AddPaymentCard"
	GophKeeperService_GetPaymentCard_FullMethodName = "/proto.GophKeeperService/GetPaymentCard"
	GophKeeperService_DelPaymentCard_FullMethodName = "/proto.GophKeeperService/DelPaymentCard"
	GophKeeperService_AddBinary_FullMethodName      = "/proto.GophKeeperService/AddBinary"
	GophKeeperService_GetBinary_FullMethodName      = "/proto.GophKeeperService/GetBinary"
	GophKeeperService_DelBinary_FullMethodName      = "/proto.GophKeeperService/DelBinary"
	GophKeeperService_AddText_FullMethodName        = "/proto.GophKeeperService/AddText"
	GophKeeperService_GetText_FullMethodName        = "/proto.GophKeeperService/GetText"
	GophKeeperService_DelText_FullMethodName        = "/proto.GophKeeperService/DelText"
	GophKeeperService_ListUserData_FullMethodName   = "/proto.GophKeeperService/ListUserData"
)

// GophKeeperServiceClient is the client API for GophKeeperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GophKeeperServiceClient interface {
	AddCredentials(ctx context.Context, in *AddCredentialsRequest, opts ...grpc.CallOption) (*AddCredentialsResponse, error)
	GetCredentials(ctx context.Context, in *GetCredentialsRequest, opts ...grpc.CallOption) (*GetCredentialsResponse, error)
	DelCredentials(ctx context.Context, in *DelCredentialsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddPaymentCard(ctx context.Context, in *AddPaymentCardRequest, opts ...grpc.CallOption) (*AddPaymentCardResponse, error)
	GetPaymentCard(ctx context.Context, in *GetPaymentCardRequest, opts ...grpc.CallOption) (*GetPaymentCardResponse, error)
	DelPaymentCard(ctx context.Context, in *DelPaymentCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddBinary(ctx context.Context, in *AddBinaryRequest, opts ...grpc.CallOption) (*AddBinaryResponse, error)
	GetBinary(ctx context.Context, in *GetBinaryRequest, opts ...grpc.CallOption) (*GetBinaryResponse, error)
	DelBinary(ctx context.Context, in *DelBinaryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddText(ctx context.Context, in *AddTextRequest, opts ...grpc.CallOption) (*AddTextResponse, error)
	GetText(ctx context.Context, in *GetTextRequest, opts ...grpc.CallOption) (*GetTextResponse, error)
	DelText(ctx context.Context, in *DelTextRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListUserData(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserDataResponse, error)
}

type gophKeeperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGophKeeperServiceClient(cc grpc.ClientConnInterface) GophKeeperServiceClient {
	return &gophKeeperServiceClient{cc}
}

func (c *gophKeeperServiceClient) AddCredentials(ctx context.Context, in *AddCredentialsRequest, opts ...grpc.CallOption) (*AddCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCredentialsResponse)
	err := c.cc.Invoke(ctx, GophKeeperService_AddCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperServiceClient) GetCredentials(ctx context.Context, in *GetCredentialsRequest, opts ...grpc.CallOption) (*GetCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialsResponse)
	err := c.cc.Invoke(ctx, GophKeeperService_GetCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperServiceClient) DelCredentials(ctx context.Context, in *DelCredentialsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GophKeeperService_DelCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperServiceClient) AddPaymentCard(ctx context.Context, in *AddPaymentCardRequest, opts ...grpc.CallOption) (*AddPaymentCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPaymentCardResponse)
	err := c.cc.Invoke(ctx, GophKeeperService_AddPaymentCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperServiceClient) GetPaymentCard(ctx context.Context, in *GetPaymentCardRequest, opts ...grpc.CallOption) (*GetPaymentCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentCardResponse)
	err := c.cc.Invoke(ctx, GophKeeperService_GetPaymentCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperServiceClient) DelPaymentCard(ctx context.Context, in *DelPaymentCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GophKeeperService_DelPaymentCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperServiceClient) AddBinary(ctx context.Context, in *AddBinaryRequest, opts ...grpc.CallOption) (*AddBinaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBinaryResponse)
	err := c.cc.Invoke(ctx, GophKeeperService_AddBinary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperServiceClient) GetBinary(ctx context.Context, in *GetBinaryRequest, opts ...grpc.CallOption) (*GetBinaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBinaryResponse)
	err := c.cc.Invoke(ctx, GophKeeperService_GetBinary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperServiceClient) DelBinary(ctx context.Context, in *DelBinaryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GophKeeperService_DelBinary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperServiceClient) AddText(ctx context.Context, in *AddTextRequest, opts ...grpc.CallOption) (*AddTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTextResponse)
	err := c.cc.Invoke(ctx, GophKeeperService_AddText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperServiceClient) GetText(ctx context.Context, in *GetTextRequest, opts ...grpc.CallOption) (*GetTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTextResponse)
	err := c.cc.Invoke(ctx, GophKeeperService_GetText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperServiceClient) DelText(ctx context.Context, in *DelTextRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GophKeeperService_DelText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperServiceClient) ListUserData(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDataResponse)
	err := c.cc.Invoke(ctx, GophKeeperService_ListUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GophKeeperServiceServer is the server API for GophKeeperService service.
// All implementations must embed UnimplementedGophKeeperServiceServer
// for forward compatibility.
type GophKeeperServiceServer interface {
	AddCredentials(context.Context, *AddCredentialsRequest) (*AddCredentialsResponse, error)
	GetCredentials(context.Context, *GetCredentialsRequest) (*GetCredentialsResponse, error)
	DelCredentials(context.Context, *DelCredentialsRequest) (*emptypb.Empty, error)
	AddPaymentCard(context.Context, *AddPaymentCardRequest) (*AddPaymentCardResponse, error)
	GetPaymentCard(context.Context, *GetPaymentCardRequest) (*GetPaymentCardResponse, error)
	DelPaymentCard(context.Context, *DelPaymentCardRequest) (*emptypb.Empty, error)
	AddBinary(context.Context, *AddBinaryRequest) (*AddBinaryResponse, error)
	GetBinary(context.Context, *GetBinaryRequest) (*GetBinaryResponse, error)
	DelBinary(context.Context, *DelBinaryRequest) (*emptypb.Empty, error)
	AddText(context.Context, *AddTextRequest) (*AddTextResponse, error)
	GetText(context.Context, *GetTextRequest) (*GetTextResponse, error)
	DelText(context.Context, *DelTextRequest) (*emptypb.Empty, error)
	ListUserData(context.Context, *emptypb.Empty) (*UserDataResponse, error)
	mustEmbedUnimplementedGophKeeperServiceServer()
}

// UnimplementedGophKeeperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGophKeeperServiceServer struct{}

func (UnimplementedGophKeeperServiceServer) AddCredentials(context.Context, *AddCredentialsRequest) (*AddCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCredentials not implemented")
}
func (UnimplementedGophKeeperServiceServer) GetCredentials(context.Context, *GetCredentialsRequest) (*GetCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredentials not implemented")
}
func (UnimplementedGophKeeperServiceServer) DelCredentials(context.Context, *DelCredentialsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelCredentials not implemented")
}
func (UnimplementedGophKeeperServiceServer) AddPaymentCard(context.Context, *AddPaymentCardRequest) (*AddPaymentCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPaymentCard not implemented")
}
func (UnimplementedGophKeeperServiceServer) GetPaymentCard(context.Context, *GetPaymentCardRequest) (*GetPaymentCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentCard not implemented")
}
func (UnimplementedGophKeeperServiceServer) DelPaymentCard(context.Context, *DelPaymentCardRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelPaymentCard not implemented")
}
func (UnimplementedGophKeeperServiceServer) AddBinary(context.Context, *AddBinaryRequest) (*AddBinaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBinary not implemented")
}
func (UnimplementedGophKeeperServiceServer) GetBinary(context.Context, *GetBinaryRequest) (*GetBinaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBinary not implemented")
}
func (UnimplementedGophKeeperServiceServer) DelBinary(context.Context, *DelBinaryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelBinary not implemented")
}
func (UnimplementedGophKeeperServiceServer) AddText(context.Context, *AddTextRequest) (*AddTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddText not implemented")
}
func (UnimplementedGophKeeperServiceServer) GetText(context.Context, *GetTextRequest) (*GetTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetText not implemented")
}
func (UnimplementedGophKeeperServiceServer) DelText(context.Context, *DelTextRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelText not implemented")
}
func (UnimplementedGophKeeperServiceServer) ListUserData(context.Context, *emptypb.Empty) (*UserDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserData not implemented")
}
func (UnimplementedGophKeeperServiceServer) mustEmbedUnimplementedGophKeeperServiceServer() {}
func (UnimplementedGophKeeperServiceServer) testEmbeddedByValue()                           {}

// UnsafeGophKeeperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GophKeeperServiceServer will
// result in compilation errors.
type UnsafeGophKeeperServiceServer interface {
	mustEmbedUnimplementedGophKeeperServiceServer()
}

func RegisterGophKeeperServiceServer(s grpc.ServiceRegistrar, srv GophKeeperServiceServer) {
	// If the following call panics, it indicates UnimplementedGophKeeperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GophKeeperService_ServiceDesc, srv)
}

func _GophKeeperService_AddCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).AddCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_AddCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).AddCredentials(ctx, req.(*AddCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperService_GetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).GetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_GetCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).GetCredentials(ctx, req.(*GetCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperService_DelCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).DelCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_DelCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).DelCredentials(ctx, req.(*DelCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperService_AddPaymentCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPaymentCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).AddPaymentCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_AddPaymentCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).AddPaymentCard(ctx, req.(*AddPaymentCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperService_GetPaymentCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).GetPaymentCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_GetPaymentCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).GetPaymentCard(ctx, req.(*GetPaymentCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperService_DelPaymentCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPaymentCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).DelPaymentCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_DelPaymentCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).DelPaymentCard(ctx, req.(*DelPaymentCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperService_AddBinary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBinaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).AddBinary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_AddBinary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).AddBinary(ctx, req.(*AddBinaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperService_GetBinary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBinaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).GetBinary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_GetBinary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).GetBinary(ctx, req.(*GetBinaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperService_DelBinary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelBinaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).DelBinary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_DelBinary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).DelBinary(ctx, req.(*DelBinaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperService_AddText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).AddText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_AddText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).AddText(ctx, req.(*AddTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperService_GetText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).GetText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_GetText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).GetText(ctx, req.(*GetTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperService_DelText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).DelText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_DelText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).DelText(ctx, req.(*DelTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeperService_ListUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServiceServer).ListUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeeperService_ListUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServiceServer).ListUserData(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GophKeeperService_ServiceDesc is the grpc.ServiceDesc for GophKeeperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GophKeeperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GophKeeperService",
	HandlerType: (*GophKeeperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCredentials",
			Handler:    _GophKeeperService_AddCredentials_Handler,
		},
		{
			MethodName: "GetCredentials",
			Handler:    _GophKeeperService_GetCredentials_Handler,
		},
		{
			MethodName: "DelCredentials",
			Handler:    _GophKeeperService_DelCredentials_Handler,
		},
		{
			MethodName: "AddPaymentCard",
			Handler:    _GophKeeperService_AddPaymentCard_Handler,
		},
		{
			MethodName: "GetPaymentCard",
			Handler:    _GophKeeperService_GetPaymentCard_Handler,
		},
		{
			MethodName: "DelPaymentCard",
			Handler:    _GophKeeperService_DelPaymentCard_Handler,
		},
		{
			MethodName: "AddBinary",
			Handler:    _GophKeeperService_AddBinary_Handler,
		},
		{
			MethodName: "GetBinary",
			Handler:    _GophKeeperService_GetBinary_Handler,
		},
		{
			MethodName: "DelBinary",
			Handler:    _GophKeeperService_DelBinary_Handler,
		},
		{
			MethodName: "AddText",
			Handler:    _GophKeeperService_AddText_Handler,
		},
		{
			MethodName: "GetText",
			Handler:    _GophKeeperService_GetText_Handler,
		},
		{
			MethodName: "DelText",
			Handler:    _GophKeeperService_DelText_Handler,
		},
		{
			MethodName: "ListUserData",
			Handler:    _GophKeeperService_ListUserData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/gophkeeper.proto",
}
