// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pkg/proto/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCredentialsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Credentials *Credentials           `protobuf:"bytes,1,opt,name=credentials"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddCredentialsRequest) Reset() {
	*x = AddCredentialsRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialsRequest) ProtoMessage() {}

func (x *AddCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddCredentialsRequest) GetCredentials() *Credentials {
	if x != nil {
		return x.xxx_hidden_Credentials
	}
	return nil
}

func (x *AddCredentialsRequest) SetCredentials(v *Credentials) {
	x.xxx_hidden_Credentials = v
}

func (x *AddCredentialsRequest) HasCredentials() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Credentials != nil
}

func (x *AddCredentialsRequest) ClearCredentials() {
	x.xxx_hidden_Credentials = nil
}

type AddCredentialsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Credentials *Credentials
}

func (b0 AddCredentialsRequest_builder) Build() *AddCredentialsRequest {
	m0 := &AddCredentialsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Credentials = b.Credentials
	return m0
}

type AddCredentialsResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,1,opt,name=alias"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddCredentialsResponse) Reset() {
	*x = AddCredentialsResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialsResponse) ProtoMessage() {}

func (x *AddCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddCredentialsResponse) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *AddCredentialsResponse) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AddCredentialsResponse) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AddCredentialsResponse) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

type AddCredentialsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias *string
}

func (b0 AddCredentialsResponse_builder) Build() *AddCredentialsResponse {
	m0 := &AddCredentialsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Alias = b.Alias
	}
	return m0
}

type GetCredentialsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,1,opt,name=alias"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetCredentialsRequest) Reset() {
	*x = GetCredentialsRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsRequest) ProtoMessage() {}

func (x *GetCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetCredentialsRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *GetCredentialsRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetCredentialsRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetCredentialsRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

type GetCredentialsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias *string
}

func (b0 GetCredentialsRequest_builder) Build() *GetCredentialsRequest {
	m0 := &GetCredentialsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Alias = b.Alias
	}
	return m0
}

type GetCredentialsResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Credentials *Credentials           `protobuf:"bytes,1,opt,name=credentials"`
	xxx_hidden_Error       *string                `protobuf:"bytes,2,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetCredentialsResponse) Reset() {
	*x = GetCredentialsResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsResponse) ProtoMessage() {}

func (x *GetCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetCredentialsResponse) GetCredentials() *Credentials {
	if x != nil {
		return x.xxx_hidden_Credentials
	}
	return nil
}

func (x *GetCredentialsResponse) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *GetCredentialsResponse) SetCredentials(v *Credentials) {
	x.xxx_hidden_Credentials = v
}

func (x *GetCredentialsResponse) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GetCredentialsResponse) HasCredentials() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Credentials != nil
}

func (x *GetCredentialsResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetCredentialsResponse) ClearCredentials() {
	x.xxx_hidden_Credentials = nil
}

func (x *GetCredentialsResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Error = nil
}

type GetCredentialsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Credentials *Credentials
	Error       *string
}

func (b0 GetCredentialsResponse_builder) Build() *GetCredentialsResponse {
	m0 := &GetCredentialsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Credentials = b.Credentials
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

type DelCredentialsRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias []string               `protobuf:"bytes,1,rep,name=alias"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DelCredentialsRequest) Reset() {
	*x = DelCredentialsRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCredentialsRequest) ProtoMessage() {}

func (x *DelCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DelCredentialsRequest) GetAlias() []string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return nil
}

func (x *DelCredentialsRequest) SetAlias(v []string) {
	x.xxx_hidden_Alias = v
}

type DelCredentialsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias []string
}

func (b0 DelCredentialsRequest_builder) Build() *DelCredentialsRequest {
	m0 := &DelCredentialsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Alias = b.Alias
	return m0
}

type AddPaymentCardRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Card *PaymentCard           `protobuf:"bytes,1,opt,name=card"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddPaymentCardRequest) Reset() {
	*x = AddPaymentCardRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentCardRequest) ProtoMessage() {}

func (x *AddPaymentCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddPaymentCardRequest) GetCard() *PaymentCard {
	if x != nil {
		return x.xxx_hidden_Card
	}
	return nil
}

func (x *AddPaymentCardRequest) SetCard(v *PaymentCard) {
	x.xxx_hidden_Card = v
}

func (x *AddPaymentCardRequest) HasCard() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Card != nil
}

func (x *AddPaymentCardRequest) ClearCard() {
	x.xxx_hidden_Card = nil
}

type AddPaymentCardRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Card *PaymentCard
}

func (b0 AddPaymentCardRequest_builder) Build() *AddPaymentCardRequest {
	m0 := &AddPaymentCardRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Card = b.Card
	return m0
}

type AddPaymentCardResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,1,opt,name=alias"`
	xxx_hidden_Error       *string                `protobuf:"bytes,2,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddPaymentCardResponse) Reset() {
	*x = AddPaymentCardResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentCardResponse) ProtoMessage() {}

func (x *AddPaymentCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddPaymentCardResponse) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *AddPaymentCardResponse) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *AddPaymentCardResponse) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AddPaymentCardResponse) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AddPaymentCardResponse) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AddPaymentCardResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AddPaymentCardResponse) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

func (x *AddPaymentCardResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Error = nil
}

type AddPaymentCardResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias *string
	Error *string
}

func (b0 AddPaymentCardResponse_builder) Build() *AddPaymentCardResponse {
	m0 := &AddPaymentCardResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

type GetPaymentCardRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,1,opt,name=alias"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetPaymentCardRequest) Reset() {
	*x = GetPaymentCardRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentCardRequest) ProtoMessage() {}

func (x *GetPaymentCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetPaymentCardRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *GetPaymentCardRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetPaymentCardRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetPaymentCardRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

type GetPaymentCardRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias *string
}

func (b0 GetPaymentCardRequest_builder) Build() *GetPaymentCardRequest {
	m0 := &GetPaymentCardRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Alias = b.Alias
	}
	return m0
}

type GetPaymentCardResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Card        *PaymentCard           `protobuf:"bytes,1,opt,name=card"`
	xxx_hidden_Error       *string                `protobuf:"bytes,2,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetPaymentCardResponse) Reset() {
	*x = GetPaymentCardResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentCardResponse) ProtoMessage() {}

func (x *GetPaymentCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetPaymentCardResponse) GetCard() *PaymentCard {
	if x != nil {
		return x.xxx_hidden_Card
	}
	return nil
}

func (x *GetPaymentCardResponse) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *GetPaymentCardResponse) SetCard(v *PaymentCard) {
	x.xxx_hidden_Card = v
}

func (x *GetPaymentCardResponse) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GetPaymentCardResponse) HasCard() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Card != nil
}

func (x *GetPaymentCardResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetPaymentCardResponse) ClearCard() {
	x.xxx_hidden_Card = nil
}

func (x *GetPaymentCardResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Error = nil
}

type GetPaymentCardResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Card  *PaymentCard
	Error *string
}

func (b0 GetPaymentCardResponse_builder) Build() *GetPaymentCardResponse {
	m0 := &GetPaymentCardResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Card = b.Card
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

type DelPaymentCardRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,1,opt,name=alias"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DelPaymentCardRequest) Reset() {
	*x = DelPaymentCardRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelPaymentCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPaymentCardRequest) ProtoMessage() {}

func (x *DelPaymentCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DelPaymentCardRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *DelPaymentCardRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DelPaymentCardRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DelPaymentCardRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

type DelPaymentCardRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias *string
}

func (b0 DelPaymentCardRequest_builder) Build() *DelPaymentCardRequest {
	m0 := &DelPaymentCardRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Alias = b.Alias
	}
	return m0
}

type AddBinaryRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Bin *Binary                `protobuf:"bytes,1,opt,name=bin"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddBinaryRequest) Reset() {
	*x = AddBinaryRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBinaryRequest) ProtoMessage() {}

func (x *AddBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddBinaryRequest) GetBin() *Binary {
	if x != nil {
		return x.xxx_hidden_Bin
	}
	return nil
}

func (x *AddBinaryRequest) SetBin(v *Binary) {
	x.xxx_hidden_Bin = v
}

func (x *AddBinaryRequest) HasBin() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Bin != nil
}

func (x *AddBinaryRequest) ClearBin() {
	x.xxx_hidden_Bin = nil
}

type AddBinaryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Bin *Binary
}

func (b0 AddBinaryRequest_builder) Build() *AddBinaryRequest {
	m0 := &AddBinaryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Bin = b.Bin
	return m0
}

type AddBinaryResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,1,opt,name=alias"`
	xxx_hidden_Error       *string                `protobuf:"bytes,2,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddBinaryResponse) Reset() {
	*x = AddBinaryResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBinaryResponse) ProtoMessage() {}

func (x *AddBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddBinaryResponse) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *AddBinaryResponse) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *AddBinaryResponse) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AddBinaryResponse) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AddBinaryResponse) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AddBinaryResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AddBinaryResponse) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

func (x *AddBinaryResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Error = nil
}

type AddBinaryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias *string
	Error *string
}

func (b0 AddBinaryResponse_builder) Build() *AddBinaryResponse {
	m0 := &AddBinaryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

type GetBinaryRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,1,opt,name=alias"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetBinaryRequest) Reset() {
	*x = GetBinaryRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinaryRequest) ProtoMessage() {}

func (x *GetBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBinaryRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *GetBinaryRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetBinaryRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetBinaryRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

type GetBinaryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias *string
}

func (b0 GetBinaryRequest_builder) Build() *GetBinaryRequest {
	m0 := &GetBinaryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Alias = b.Alias
	}
	return m0
}

type GetBinaryResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Bin         *Binary                `protobuf:"bytes,1,opt,name=bin"`
	xxx_hidden_Error       *string                `protobuf:"bytes,2,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetBinaryResponse) Reset() {
	*x = GetBinaryResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinaryResponse) ProtoMessage() {}

func (x *GetBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBinaryResponse) GetBin() *Binary {
	if x != nil {
		return x.xxx_hidden_Bin
	}
	return nil
}

func (x *GetBinaryResponse) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *GetBinaryResponse) SetBin(v *Binary) {
	x.xxx_hidden_Bin = v
}

func (x *GetBinaryResponse) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GetBinaryResponse) HasBin() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Bin != nil
}

func (x *GetBinaryResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetBinaryResponse) ClearBin() {
	x.xxx_hidden_Bin = nil
}

func (x *GetBinaryResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Error = nil
}

type GetBinaryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Bin   *Binary
	Error *string
}

func (b0 GetBinaryResponse_builder) Build() *GetBinaryResponse {
	m0 := &GetBinaryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Bin = b.Bin
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

type DelBinaryRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,1,opt,name=alias"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DelBinaryRequest) Reset() {
	*x = DelBinaryRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelBinaryRequest) ProtoMessage() {}

func (x *DelBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DelBinaryRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *DelBinaryRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DelBinaryRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DelBinaryRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

type DelBinaryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias *string
}

func (b0 DelBinaryRequest_builder) Build() *DelBinaryRequest {
	m0 := &DelBinaryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Alias = b.Alias
	}
	return m0
}

type AddTextRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Text *Text                  `protobuf:"bytes,1,opt,name=text"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddTextRequest) Reset() {
	*x = AddTextRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTextRequest) ProtoMessage() {}

func (x *AddTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddTextRequest) GetText() *Text {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return nil
}

func (x *AddTextRequest) SetText(v *Text) {
	x.xxx_hidden_Text = v
}

func (x *AddTextRequest) HasText() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Text != nil
}

func (x *AddTextRequest) ClearText() {
	x.xxx_hidden_Text = nil
}

type AddTextRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Text *Text
}

func (b0 AddTextRequest_builder) Build() *AddTextRequest {
	m0 := &AddTextRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Text = b.Text
	return m0
}

type AddTextResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,1,opt,name=alias"`
	xxx_hidden_Error       *string                `protobuf:"bytes,2,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddTextResponse) Reset() {
	*x = AddTextResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTextResponse) ProtoMessage() {}

func (x *AddTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddTextResponse) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *AddTextResponse) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *AddTextResponse) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AddTextResponse) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AddTextResponse) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AddTextResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AddTextResponse) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

func (x *AddTextResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Error = nil
}

type AddTextResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias *string
	Error *string
}

func (b0 AddTextResponse_builder) Build() *AddTextResponse {
	m0 := &AddTextResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

type GetTextRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,1,opt,name=alias"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetTextRequest) Reset() {
	*x = GetTextRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextRequest) ProtoMessage() {}

func (x *GetTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetTextRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *GetTextRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetTextRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetTextRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

type GetTextRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias *string
}

func (b0 GetTextRequest_builder) Build() *GetTextRequest {
	m0 := &GetTextRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Alias = b.Alias
	}
	return m0
}

type GetTextResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Text        *Text                  `protobuf:"bytes,1,opt,name=text"`
	xxx_hidden_Error       *string                `protobuf:"bytes,2,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetTextResponse) Reset() {
	*x = GetTextResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextResponse) ProtoMessage() {}

func (x *GetTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetTextResponse) GetText() *Text {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return nil
}

func (x *GetTextResponse) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *GetTextResponse) SetText(v *Text) {
	x.xxx_hidden_Text = v
}

func (x *GetTextResponse) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GetTextResponse) HasText() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Text != nil
}

func (x *GetTextResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetTextResponse) ClearText() {
	x.xxx_hidden_Text = nil
}

func (x *GetTextResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Error = nil
}

type GetTextResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Text  *Text
	Error *string
}

func (b0 GetTextResponse_builder) Build() *GetTextResponse {
	m0 := &GetTextResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Text = b.Text
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

type DelTextRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,1,opt,name=alias"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DelTextRequest) Reset() {
	*x = DelTextRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTextRequest) ProtoMessage() {}

func (x *DelTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DelTextRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *DelTextRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DelTextRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DelTextRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

type DelTextRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias *string
}

func (b0 DelTextRequest_builder) Build() *DelTextRequest {
	m0 := &DelTextRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Alias = b.Alias
	}
	return m0
}

type UserDataResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Credentials *[]*Credentials        `protobuf:"bytes,1,rep,name=credentials"`
	xxx_hidden_PaymentCard *[]*PaymentCard        `protobuf:"bytes,2,rep,name=paymentCard"`
	xxx_hidden_Binary      *[]*Binary             `protobuf:"bytes,3,rep,name=binary"`
	xxx_hidden_Text        *[]*Text               `protobuf:"bytes,4,rep,name=text"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserDataResponse) Reset() {
	*x = UserDataResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataResponse) ProtoMessage() {}

func (x *UserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserDataResponse) GetCredentials() []*Credentials {
	if x != nil {
		if x.xxx_hidden_Credentials != nil {
			return *x.xxx_hidden_Credentials
		}
	}
	return nil
}

func (x *UserDataResponse) GetPaymentCard() []*PaymentCard {
	if x != nil {
		if x.xxx_hidden_PaymentCard != nil {
			return *x.xxx_hidden_PaymentCard
		}
	}
	return nil
}

func (x *UserDataResponse) GetBinary() []*Binary {
	if x != nil {
		if x.xxx_hidden_Binary != nil {
			return *x.xxx_hidden_Binary
		}
	}
	return nil
}

func (x *UserDataResponse) GetText() []*Text {
	if x != nil {
		if x.xxx_hidden_Text != nil {
			return *x.xxx_hidden_Text
		}
	}
	return nil
}

func (x *UserDataResponse) SetCredentials(v []*Credentials) {
	x.xxx_hidden_Credentials = &v
}

func (x *UserDataResponse) SetPaymentCard(v []*PaymentCard) {
	x.xxx_hidden_PaymentCard = &v
}

func (x *UserDataResponse) SetBinary(v []*Binary) {
	x.xxx_hidden_Binary = &v
}

func (x *UserDataResponse) SetText(v []*Text) {
	x.xxx_hidden_Text = &v
}

type UserDataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Credentials []*Credentials
	PaymentCard []*PaymentCard
	Binary      []*Binary
	Text        []*Text
}

func (b0 UserDataResponse_builder) Build() *UserDataResponse {
	m0 := &UserDataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Credentials = &b.Credentials
	x.xxx_hidden_PaymentCard = &b.PaymentCard
	x.xxx_hidden_Binary = &b.Binary
	x.xxx_hidden_Text = &b.Text
	return m0
}

type Credentials struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,3,opt,name=alias"`
	xxx_hidden_Info        *string                `protobuf:"bytes,4,opt,name=info"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Credentials) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *Credentials) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *Credentials) GetInfo() string {
	if x != nil {
		if x.xxx_hidden_Info != nil {
			return *x.xxx_hidden_Info
		}
		return ""
	}
	return ""
}

func (x *Credentials) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Credentials) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Credentials) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Credentials) SetInfo(v string) {
	x.xxx_hidden_Info = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Credentials) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Credentials) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Credentials) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Credentials) HasInfo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Credentials) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *Credentials) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

func (x *Credentials) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Alias = nil
}

func (x *Credentials) ClearInfo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Info = nil
}

type Credentials_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    *string
	Password *string
	Alias    *string
	Info     *string
}

func (b0 Credentials_builder) Build() *Credentials {
	m0 := &Credentials{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Password = b.Password
	}
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Info != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Info = b.Info
	}
	return m0
}

type PaymentCard struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      *string                `protobuf:"bytes,1,opt,name=number"`
	xxx_hidden_ExpMonth    int32                  `protobuf:"zigzag32,2,opt,name=expMonth"`
	xxx_hidden_ExpYear     int32                  `protobuf:"zigzag32,3,opt,name=expYear"`
	xxx_hidden_Cvv         *string                `protobuf:"bytes,4,opt,name=cvv"`
	xxx_hidden_Holder      *string                `protobuf:"bytes,5,opt,name=holder"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,6,opt,name=alias"`
	xxx_hidden_Info        *string                `protobuf:"bytes,7,opt,name=info"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PaymentCard) Reset() {
	*x = PaymentCard{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCard) ProtoMessage() {}

func (x *PaymentCard) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PaymentCard) GetNumber() string {
	if x != nil {
		if x.xxx_hidden_Number != nil {
			return *x.xxx_hidden_Number
		}
		return ""
	}
	return ""
}

func (x *PaymentCard) GetExpMonth() int32 {
	if x != nil {
		return x.xxx_hidden_ExpMonth
	}
	return 0
}

func (x *PaymentCard) GetExpYear() int32 {
	if x != nil {
		return x.xxx_hidden_ExpYear
	}
	return 0
}

func (x *PaymentCard) GetCvv() string {
	if x != nil {
		if x.xxx_hidden_Cvv != nil {
			return *x.xxx_hidden_Cvv
		}
		return ""
	}
	return ""
}

func (x *PaymentCard) GetHolder() string {
	if x != nil {
		if x.xxx_hidden_Holder != nil {
			return *x.xxx_hidden_Holder
		}
		return ""
	}
	return ""
}

func (x *PaymentCard) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *PaymentCard) GetInfo() string {
	if x != nil {
		if x.xxx_hidden_Info != nil {
			return *x.xxx_hidden_Info
		}
		return ""
	}
	return ""
}

func (x *PaymentCard) SetNumber(v string) {
	x.xxx_hidden_Number = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *PaymentCard) SetExpMonth(v int32) {
	x.xxx_hidden_ExpMonth = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *PaymentCard) SetExpYear(v int32) {
	x.xxx_hidden_ExpYear = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *PaymentCard) SetCvv(v string) {
	x.xxx_hidden_Cvv = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *PaymentCard) SetHolder(v string) {
	x.xxx_hidden_Holder = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *PaymentCard) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *PaymentCard) SetInfo(v string) {
	x.xxx_hidden_Info = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *PaymentCard) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PaymentCard) HasExpMonth() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PaymentCard) HasExpYear() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PaymentCard) HasCvv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PaymentCard) HasHolder() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *PaymentCard) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *PaymentCard) HasInfo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *PaymentCard) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = nil
}

func (x *PaymentCard) ClearExpMonth() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ExpMonth = 0
}

func (x *PaymentCard) ClearExpYear() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ExpYear = 0
}

func (x *PaymentCard) ClearCvv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Cvv = nil
}

func (x *PaymentCard) ClearHolder() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Holder = nil
}

func (x *PaymentCard) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Alias = nil
}

func (x *PaymentCard) ClearInfo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Info = nil
}

type PaymentCard_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number   *string
	ExpMonth *int32
	ExpYear  *int32
	Cvv      *string
	Holder   *string
	Alias    *string
	Info     *string
}

func (b0 PaymentCard_builder) Build() *PaymentCard {
	m0 := &PaymentCard{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Number = b.Number
	}
	if b.ExpMonth != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_ExpMonth = *b.ExpMonth
	}
	if b.ExpYear != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_ExpYear = *b.ExpYear
	}
	if b.Cvv != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Cvv = b.Cvv
	}
	if b.Holder != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Holder = b.Holder
	}
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Info != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_Info = b.Info
	}
	return m0
}

type Binary struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,2,opt,name=alias"`
	xxx_hidden_Info        *string                `protobuf:"bytes,3,opt,name=info"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Binary) Reset() {
	*x = Binary{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binary) ProtoMessage() {}

func (x *Binary) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Binary) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Binary) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *Binary) GetInfo() string {
	if x != nil {
		if x.xxx_hidden_Info != nil {
			return *x.xxx_hidden_Info
		}
		return ""
	}
	return ""
}

func (x *Binary) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Binary) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Binary) SetInfo(v string) {
	x.xxx_hidden_Info = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Binary) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Binary) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Binary) HasInfo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Binary) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

func (x *Binary) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

func (x *Binary) ClearInfo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Info = nil
}

type Binary_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data  []byte
	Alias *string
	Info  *string
}

func (b0 Binary_builder) Build() *Binary {
	m0 := &Binary{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Data = b.Data
	}
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Info != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Info = b.Info
	}
	return m0
}

type Text struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        *string                `protobuf:"bytes,1,opt,name=data"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,2,opt,name=alias"`
	xxx_hidden_Info        *string                `protobuf:"bytes,3,opt,name=info"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Text) GetData() string {
	if x != nil {
		if x.xxx_hidden_Data != nil {
			return *x.xxx_hidden_Data
		}
		return ""
	}
	return ""
}

func (x *Text) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *Text) GetInfo() string {
	if x != nil {
		if x.xxx_hidden_Info != nil {
			return *x.xxx_hidden_Info
		}
		return ""
	}
	return ""
}

func (x *Text) SetData(v string) {
	x.xxx_hidden_Data = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Text) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Text) SetInfo(v string) {
	x.xxx_hidden_Info = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Text) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Text) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Text) HasInfo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Text) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

func (x *Text) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

func (x *Text) ClearInfo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Info = nil
}

type Text_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data  *string
	Alias *string
	Info  *string
}

func (b0 Text_builder) Build() *Text {
	m0 := &Text{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Data = b.Data
	}
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Info != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Info = b.Info
	}
	return m0
}

var File_pkg_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_pkg_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/proto/gophkeeper.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"M\n" +
	"\x15AddCredentialsRequest\x124\n" +
	"\vcredentials\x18\x01 \x01(\v2\x12.proto.CredentialsR\vcredentials\".\n" +
	"\x16AddCredentialsResponse\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"-\n" +
	"\x15GetCredentialsRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"d\n" +
	"\x16GetCredentialsResponse\x124\n" +
	"\vcredentials\x18\x01 \x01(\v2\x12.proto.CredentialsR\vcredentials\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x15DelCredentialsRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x03(\tR\x05alias\"?\n" +
	"\x15AddPaymentCardRequest\x12&\n" +
	"\x04card\x18\x01 \x01(\v2\x12.proto.PaymentCardR\x04card\"D\n" +
	"\x16AddPaymentCardResponse\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x15GetPaymentCardRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"V\n" +
	"\x16GetPaymentCardResponse\x12&\n" +
	"\x04card\x18\x01 \x01(\v2\x12.proto.PaymentCardR\x04card\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x15DelPaymentCardRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"3\n" +
	"\x10AddBinaryRequest\x12\x1f\n" +
	"\x03bin\x18\x01 \x01(\v2\r.proto.BinaryR\x03bin\"?\n" +
	"\x11AddBinaryResponse\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"(\n" +
	"\x10GetBinaryRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"J\n" +
	"\x11GetBinaryResponse\x12\x1f\n" +
	"\x03bin\x18\x01 \x01(\v2\r.proto.BinaryR\x03bin\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"(\n" +
	"\x10DelBinaryRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"1\n" +
	"\x0eAddTextRequest\x12\x1f\n" +
	"\x04text\x18\x01 \x01(\v2\v.proto.TextR\x04text\"=\n" +
	"\x0fAddTextResponse\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x0eGetTextRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"H\n" +
	"\x0fGetTextResponse\x12\x1f\n" +
	"\x04text\x18\x01 \x01(\v2\v.proto.TextR\x04text\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x0eDelTextRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"\xc6\x01\n" +
	"\x10UserDataResponse\x124\n" +
	"\vcredentials\x18\x01 \x03(\v2\x12.proto.CredentialsR\vcredentials\x124\n" +
	"\vpaymentCard\x18\x02 \x03(\v2\x12.proto.PaymentCardR\vpaymentCard\x12%\n" +
	"\x06binary\x18\x03 \x03(\v2\r.proto.BinaryR\x06binary\x12\x1f\n" +
	"\x04text\x18\x04 \x03(\v2\v.proto.TextR\x04text\"i\n" +
	"\vCredentials\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x12\n" +
	"\x04info\x18\x04 \x01(\tR\x04info\"\xaf\x01\n" +
	"\vPaymentCard\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x1a\n" +
	"\bexpMonth\x18\x02 \x01(\x11R\bexpMonth\x12\x18\n" +
	"\aexpYear\x18\x03 \x01(\x11R\aexpYear\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\x12\x16\n" +
	"\x06holder\x18\x05 \x01(\tR\x06holder\x12\x14\n" +
	"\x05alias\x18\x06 \x01(\tR\x05alias\x12\x12\n" +
	"\x04info\x18\a \x01(\tR\x04info\"F\n" +
	"\x06Binary\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\"D\n" +
	"\x04Text\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info2\x8c\a\n" +
	"\x11GophKeeperService\x12M\n" +
	"\x0eAddCredentials\x12\x1c.proto.AddCredentialsRequest\x1a\x1d.proto.AddCredentialsResponse\x12M\n" +
	"\x0eGetCredentials\x12\x1c.proto.GetCredentialsRequest\x1a\x1d.proto.GetCredentialsResponse\x12F\n" +
	"\x0eDelCredentials\x12\x1c.proto.DelCredentialsRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x0eAddPaymentCard\x12\x1c.proto.AddPaymentCardRequest\x1a\x1d.proto.AddPaymentCardResponse\x12M\n" +
	"\x0eGetPaymentCard\x12\x1c.proto.GetPaymentCardRequest\x1a\x1d.proto.GetPaymentCardResponse\x12F\n" +
	"\x0eDelPaymentCard\x12\x1c.proto.DelPaymentCardRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\tAddBinary\x12\x17.proto.AddBinaryRequest\x1a\x18.proto.AddBinaryResponse\x12>\n" +
	"\tGetBinary\x12\x17.proto.GetBinaryRequest\x1a\x18.proto.GetBinaryResponse\x12<\n" +
	"\tDelBinary\x12\x17.proto.DelBinaryRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\aAddText\x12\x15.proto.AddTextRequest\x1a\x16.proto.AddTextResponse\x128\n" +
	"\aGetText\x12\x15.proto.GetTextRequest\x1a\x16.proto.GetTextResponse\x128\n" +
	"\aDelText\x12\x15.proto.DelTextRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\fListUserData\x12\x16.google.protobuf.Empty\x1a\x17.proto.UserDataResponseB(Z&github.com/Di-nis/gophKeeper/pkg/protob\beditionsp\xe8\a"

var file_pkg_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pkg_proto_gophkeeper_proto_goTypes = []any{
	(*AddCredentialsRequest)(nil),  // 0: proto.AddCredentialsRequest
	(*AddCredentialsResponse)(nil), // 1: proto.AddCredentialsResponse
	(*GetCredentialsRequest)(nil),  // 2: proto.GetCredentialsRequest
	(*GetCredentialsResponse)(nil), // 3: proto.GetCredentialsResponse
	(*DelCredentialsRequest)(nil),  // 4: proto.DelCredentialsRequest
	(*AddPaymentCardRequest)(nil),  // 5: proto.AddPaymentCardRequest
	(*AddPaymentCardResponse)(nil), // 6: proto.AddPaymentCardResponse
	(*GetPaymentCardRequest)(nil),  // 7: proto.GetPaymentCardRequest
	(*GetPaymentCardResponse)(nil), // 8: proto.GetPaymentCardResponse
	(*DelPaymentCardRequest)(nil),  // 9: proto.DelPaymentCardRequest
	(*AddBinaryRequest)(nil),       // 10: proto.AddBinaryRequest
	(*AddBinaryResponse)(nil),      // 11: proto.AddBinaryResponse
	(*GetBinaryRequest)(nil),       // 12: proto.GetBinaryRequest
	(*GetBinaryResponse)(nil),      // 13: proto.GetBinaryResponse
	(*DelBinaryRequest)(nil),       // 14: proto.DelBinaryRequest
	(*AddTextRequest)(nil),         // 15: proto.AddTextRequest
	(*AddTextResponse)(nil),        // 16: proto.AddTextResponse
	(*GetTextRequest)(nil),         // 17: proto.GetTextRequest
	(*GetTextResponse)(nil),        // 18: proto.GetTextResponse
	(*DelTextRequest)(nil),         // 19: proto.DelTextRequest
	(*UserDataResponse)(nil),       // 20: proto.UserDataResponse
	(*Credentials)(nil),            // 21: proto.Credentials
	(*PaymentCard)(nil),            // 22: proto.PaymentCard
	(*Binary)(nil),                 // 23: proto.Binary
	(*Text)(nil),                   // 24: proto.Text
	(*emptypb.Empty)(nil),          // 25: google.protobuf.Empty
}
var file_pkg_proto_gophkeeper_proto_depIdxs = []int32{
	21, // 0: proto.AddCredentialsRequest.credentials:type_name -> proto.Credentials
	21, // 1: proto.GetCredentialsResponse.credentials:type_name -> proto.Credentials
	22, // 2: proto.AddPaymentCardRequest.card:type_name -> proto.PaymentCard
	22, // 3: proto.GetPaymentCardResponse.card:type_name -> proto.PaymentCard
	23, // 4: proto.AddBinaryRequest.bin:type_name -> proto.Binary
	23, // 5: proto.GetBinaryResponse.bin:type_name -> proto.Binary
	24, // 6: proto.AddTextRequest.text:type_name -> proto.Text
	24, // 7: proto.GetTextResponse.text:type_name -> proto.Text
	21, // 8: proto.UserDataResponse.credentials:type_name -> proto.Credentials
	22, // 9: proto.UserDataResponse.paymentCard:type_name -> proto.PaymentCard
	23, // 10: proto.UserDataResponse.binary:type_name -> proto.Binary
	24, // 11: proto.UserDataResponse.text:type_name -> proto.Text
	0,  // 12: proto.GophKeeperService.AddCredentials:input_type -> proto.AddCredentialsRequest
	2,  // 13: proto.GophKeeperService.GetCredentials:input_type -> proto.GetCredentialsRequest
	4,  // 14: proto.GophKeeperService.DelCredentials:input_type -> proto.DelCredentialsRequest
	5,  // 15: proto.GophKeeperService.AddPaymentCard:input_type -> proto.AddPaymentCardRequest
	7,  // 16: proto.GophKeeperService.GetPaymentCard:input_type -> proto.GetPaymentCardRequest
	9,  // 17: proto.GophKeeperService.DelPaymentCard:input_type -> proto.DelPaymentCardRequest
	10, // 18: proto.GophKeeperService.AddBinary:input_type -> proto.AddBinaryRequest
	12, // 19: proto.GophKeeperService.GetBinary:input_type -> proto.GetBinaryRequest
	14, // 20: proto.GophKeeperService.DelBinary:input_type -> proto.DelBinaryRequest
	15, // 21: proto.GophKeeperService.AddText:input_type -> proto.AddTextRequest
	17, // 22: proto.GophKeeperService.GetText:input_type -> proto.GetTextRequest
	19, // 23: proto.GophKeeperService.DelText:input_type -> proto.DelTextRequest
	25, // 24: proto.GophKeeperService.ListUserData:input_type -> google.protobuf.Empty
	1,  // 25: proto.GophKeeperService.AddCredentials:output_type -> proto.AddCredentialsResponse
	3,  // 26: proto.GophKeeperService.GetCredentials:output_type -> proto.GetCredentialsResponse
	25, // 27: proto.GophKeeperService.DelCredentials:output_type -> google.protobuf.Empty
	6,  // 28: proto.GophKeeperService.AddPaymentCard:output_type -> proto.AddPaymentCardResponse
	8,  // 29: proto.GophKeeperService.GetPaymentCard:output_type -> proto.GetPaymentCardResponse
	25, // 30: proto.GophKeeperService.DelPaymentCard:output_type -> google.protobuf.Empty
	11, // 31: proto.GophKeeperService.AddBinary:output_type -> proto.AddBinaryResponse
	13, // 32: proto.GophKeeperService.GetBinary:output_type -> proto.GetBinaryResponse
	25, // 33: proto.GophKeeperService.DelBinary:output_type -> google.protobuf.Empty
	16, // 34: proto.GophKeeperService.AddText:output_type -> proto.AddTextResponse
	18, // 35: proto.GophKeeperService.GetText:output_type -> proto.GetTextResponse
	25, // 36: proto.GophKeeperService.DelText:output_type -> google.protobuf.Empty
	20, // 37: proto.GophKeeperService.ListUserData:output_type -> proto.UserDataResponse
	25, // [25:38] is the sub-list for method output_type
	12, // [12:25] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_proto_gophkeeper_proto_init() }
func file_pkg_proto_gophkeeper_proto_init() {
	if File_pkg_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_gophkeeper_proto_rawDesc), len(file_pkg_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_pkg_proto_gophkeeper_proto_depIdxs,
		MessageInfos:      file_pkg_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_pkg_proto_gophkeeper_proto = out.File
	file_pkg_proto_gophkeeper_proto_goTypes = nil
	file_pkg_proto_gophkeeper_proto_depIdxs = nil
}
